version: 1.0.{build}
image:
  - Visual Studio 2017

environment:
  PYTHON: C:\\Python36-x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip pipenv"
  - "pipenv --python %PYTHON% install --dev"

build: off

test_script:
  - "pipenv run python -m pytest"

# TODO: Add Building and tests around the build.  Also auto push to github.
# after_test:
#   - "pipenv run pyinstaller process_reports.spec"

# artifacts:
#   - path: dist\*
