version: 1.0.{build}
image:
  - Visual Studio 2017

environment:
  matrix:
  - PYTHON: C:\\Python36-x64
  - PYTHON: C:\\Python36

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip pipenv"
  - "pipenv install --dev"

build: off

test_script:
  - "pipenv run pytest"

after_test:
  - "pipenv run pyinstaller process_reports.spec"

artifacts:
  - path: dist\*
