version: 1.0.{build}
image:
  - Visual Studio 2017

environment:
  PYTHON: C:\\Python36-x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # TODO: this isn't smart enough to grab the right python...need to fix that.
  - "python -m pip install -U pip pipenv"
  - "pipenv install --dev"

build: off

test_script:
  - "pipenv run python -m pytest"

after_test:
  - "pipenv run pyinstaller process_reports.spec"

artifacts:
  - path: dist\*
